// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack.OrmLite;

namespace Boiler.Models
{
	[Alias("Fielding")]
    public partial class Fielding : IHasId<int>, IHasAudit
    {
        [Alias("FieldingId")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public int PlayerId { get; set; }
        public decimal? Mechanics { get; set; }
        public decimal? Range { get; set; }
        public decimal? Hands { get; set; }
        public decimal? ArmStrength { get; set; }
        public string FieldingNote { get; set; }
        [Required]
        public string CreatedBy { get; set; }
        [Required]
        public DateTime CreatedDate { get; set; }
	}
}
#pragma warning restore 1591
