
// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `App`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `server=.;database=Journey;Integrated Security=true`
//     Schema:                 ``
//     Include Views:          `True`

//     Factory Name:          `SqlClientFactory`


