// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack.OrmLite;

namespace Boiler.Models
{
	[Alias("Player")]
    public partial class Player : IHasId<int>, IHasAudit
    {
        [Alias("PlayerId")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public string PlayerNumber { get; set; }
        [Required]
        public string PlayerName { get; set; }
        [Required]
        public int LeagueAge { get; set; }
        public string LeaguePlayed { get; set; }
        public string ASMI { get; set; }
        public int? HBB { get; set; }
        public int? HSO { get; set; }
        public decimal? HAVG { get; set; }
        public decimal? HOPS { get; set; }
        public decimal? PIP { get; set; }
        public int? PBB { get; set; }
        public int? PSO { get; set; }
        public decimal? PWHIP { get; set; }
        public string Size { get; set; }
        public string Throws { get; set; }
        public string Bats { get; set; }
        public string PlayerNote { get; set; }
        [Required]
        public string CreatedBy { get; set; }
        [Required]
        public DateTime CreatedDate { get; set; }
	}
}
#pragma warning restore 1591
